version: '3.7'

services:
  outlaymanagerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro