version: '3.7'
services:
  outlaymanagerapi:
    image: ${DOCKER_REGISTRY-}outlaymanagerapi
    build:
      context: .
      dockerfile: OutlayManagerAPI/Dockerfile
    ports:
     - 5024:5024
    environment:
     - IdentityServerURL=http://identityserver:6001     
     - ASPNETCORE_ENVIRONMENT=Production 
     - ConnectionStrings__PathBDConnection=Filename=DataBaseFile/OutlayDataBase.db;
    volumes:
     - C:\Projects\OutlayApplication\DataBaseFile:/app/DataBaseFile
       
  identityserver:
   image: ${DOCKER_REGISTRY-}identityserver
   build:
    context: .
    dockerfile: IdentityServer/Dockerfile
   environment:
    - ASPNETCORE_ENVIRONMENT=Production